spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/oauth2/jwks
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://postgres:5432/edu
minio:
  accessKey: ssPdvjHHliFcN99CMf5z
  secretKey: 7c5wnimpGFyq36EwLfWjTL03tE5PKh8NiWcAHw4J
  endpoint: http://49.234.53.94:30202
idp:
  url: http://localhost:8000
