server:
  port: 8201
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/oauth2/jwks
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/edu
  jpa:
    properties:
      hibernate:
        show_sql: true
minio:
  accessKey: # accessKey
  secretKey: # secretKey
  endpoint: # endpoint
idp:
  url: http://localhost:8000
logging:
  level:
    org.springframework.security: trace
